### ISSUE TITLE
Question on opa test options

### ISSUE THREAD

**Issue by leefernandes** [ticketmaster/rules_opa#41]
Is it possible to pass options to `opa test`?

https://www.openpolicyagent.org/docs/latest/cli/#options-12

Specifically we're trying to get additional info from test failures, so maybe `--verbose` and `--explain` would be useful.

**Comment by leefernandes** [comment]
Is how you've defined `--strict` as an arg in [opa_check](https://github.com/ticketmaster/rules_opa/blob/16458b1ccb3906861cb8add5ba49ec66497a4df7/opa/private/opa_check.bzl#L38) be the pattern to follow for adding `--verbose` and `--explain` to [opa_test](https://github.com/ticketmaster/rules_opa/blob/main/opa/private/opa_test.bzl)

**Comment by ffortier** [comment]
Hello. Good question. I see 3 1/2 possibilities

1. We can add dedicated attributes just as you suggested, similar to the `--strict` flag.
2. We can add a more general `opts` attribute for arbitrary options. 
3. We can add flags for the command line, something like `--@rules_opa//:test_verbose` and `--@rules_opa//:test_explain` so that I can be set dynamically
3.5. Reuse some exiting flag provided by bazel

What do you think would work best for you?

**Comment by leefernandes** [comment]
I think I'd be familiar with how to apply 1.

```bazel
opa_test(
    name = "opa_lib_test",
    size = "small",
    srcs = glob(["opa/**/*_test.rego"]),
    deps = [":opa_lib"],
    strict = True,
)
```

I'm not familiar with how the others would be accomplished, but otherwise don't have a strong preference other than a desire to get increased visibility of failing tests.  As it currently is we don't get any details beyond that the test FAILED.  And are looking for typical information such as the values that were compared being output.
